### ISSUE TITLE
fs-extra missing when upgrading from 1.4.1 to 1.4.3

### ISSUE THREAD

**Issue by christophemenager** [Malaa-tech/expo-custom-assets#13]
`Error: Cannot find module 'fs-extra'`

fs-extra should not be expected to be installed within the project but be a dependency of this package instead I guess

**Comment by christophemenager** [comment]
`1.4.4` fixes the issue ! 🙏
